services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3308
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql-data: